version: "3.9"
services:
    db:
        image: postgres:13-alpine
        container_name: "postgres_local"
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env
    web:
        restart: always
        build: .
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/code
        expose:
            - "8000"
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - db
        links:
            - db
volumes:
    postgres_data:
        name: postgres_local_data
