"""Remove uuid column
Revision ID: 1e6ee39204b2
Revises: 5e7f3314dbb1
Create Date: 2021-08-28 17:14:16.883964
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic
revision = '1e6ee39204b2'
down_revision = '5e7f3314dbb1'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_info_user_uuid', table_name='user_info')
    op.drop_column('user_info', 'user_uuid')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('user_uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.create_index('ix_user_info_user_uuid', 'user_info', ['user_uuid'], unique=False)
    # ### end Alembic commands ###