"""Added profile image extension
Revision ID: 5e7f3314dbb1
Revises: 94c04896d351
Create Date: 2021-07-31 21:37:27.924518
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '5e7f3314dbb1'
down_revision = '94c04896d351'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('profile_image_extension', sa.String(), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'profile_image_extension')
    # ### end Alembic commands ###