"""Added profile image upload time column
Revision ID: 611903f521e6
Revises: 74f62f40a9d9
Create Date: 2021-07-07 03:48:01.402445
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '611903f521e6'
down_revision = '74f62f40a9d9'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('profile_image_uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'profile_image_uploaded_at')
    # ### end Alembic commands ###