"""Added email_public
Revision ID: 74f62f40a9d9
Revises: c60ddfae9002
Create Date: 2021-07-04 21:00:22.454196
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '74f62f40a9d9'
down_revision = 'c60ddfae9002'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('email_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'email_public')
    # ### end Alembic commands ###