"""Initial revision
Revision ID: c6b6706d84ab
Revises: 
Create Date: 2021-12-10 04:23:04.598667
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic
revision = 'c6b6706d84ab'
down_revision = '5c609fc541f1'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('dob_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('share_mode', sa.String(), server_default='default_none', nullable=False),
    sa.Column('domain_allow_array', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('domain_deny_array', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('gender', sa.String(), server_default='', nullable=False),
    sa.Column('gender_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('school', sa.String(), server_default='', nullable=False),
    sa.Column('school_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('work', sa.String(), server_default='', nullable=False),
    sa.Column('work_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('location', sa.String(), server_default='', nullable=False),
    sa.Column('location_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('profile_image_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('profile_image_extension', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_table_user_id'), 'user_table', ['user_id'], unique=False)
    op.create_table('friendship_table',
    sa.Column('user_id1', sa.String(), nullable=False),
    sa.Column('user_id2', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id1'], ['user_table.user_id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('user_id1', 'user_id2')
    )
    op.create_index(op.f('ix_friendship_table_user_id1'), 'friendship_table', ['user_id1'], unique=False)
    op.create_index(op.f('ix_friendship_table_user_id2'), 'friendship_table', ['user_id2'], unique=False)
    op.create_table('share_notification_table',
    sa.Column('event_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_share_notification_table_event_id'), 'share_notification_table', ['event_id'], unique=False)
    op.create_index(op.f('ix_share_notification_table_user_id'), 'share_notification_table', ['user_id'], unique=False)
    op.create_table('share_notification_seen_table',
    sa.Column('event_id', postgresql.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['share_notification_table.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_index(op.f('ix_share_notification_seen_table_event_id'), 'share_notification_seen_table', ['event_id'], unique=False)
    op.create_index(op.f('ix_share_notification_seen_table_user_id'), 'share_notification_seen_table', ['user_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_notification_seen_table_user_id'), table_name='share_notification_seen_table')
    op.drop_index(op.f('ix_share_notification_seen_table_event_id'), table_name='share_notification_seen_table')
    op.drop_table('share_notification_seen_table')
    op.drop_index(op.f('ix_share_notification_table_user_id'), table_name='share_notification_table')
    op.drop_index(op.f('ix_share_notification_table_event_id'), table_name='share_notification_table')
    op.drop_table('share_notification_table')
    op.drop_index(op.f('ix_friendship_table_user_id2'), table_name='friendship_table')
    op.drop_index(op.f('ix_friendship_table_user_id1'), table_name='friendship_table')
    op.drop_table('friendship_table')
    op.drop_index(op.f('ix_user_table_user_id'), table_name='user_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###