"""Initial commit
Revision ID: 94c04896d351
Revises: 
Create Date: 2021-07-30 04:04:51.758711
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic
revision = '94c04896d351'
down_revision = None
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('dob_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('share_mode', sa.String(), server_default='default_all', nullable=False),
    sa.Column('domain_allow_array', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('domain_deny_array', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('gender_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('school', sa.String(), server_default='', nullable=False),
    sa.Column('school_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('work', sa.String(), server_default='', nullable=False),
    sa.Column('work_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('location', sa.String(), server_default='', nullable=False),
    sa.Column('location_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('profile_image_uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_info_user_id'), 'user_info', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_info_user_uuid'), 'user_info', ['user_uuid'], unique=True)
    op.create_table('friendship',
    sa.Column('user_id1', sa.String(), nullable=False),
    sa.Column('user_id2', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id1'], ['user_info.user_id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('user_id1', 'user_id2')
    )
    op.create_index(op.f('ix_friendship_user_id1'), 'friendship', ['user_id1'], unique=False)
    op.create_index(op.f('ix_friendship_user_id2'), 'friendship', ['user_id2'], unique=False)
    op.create_table('user_url_history',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('page_title', sa.String(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'url', 'accessed_at')
    )
    op.create_index(op.f('ix_user_url_history_user_id'), 'user_url_history', ['user_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_url_history_user_id'), table_name='user_url_history')
    op.drop_table('user_url_history')
    op.drop_index(op.f('ix_friendship_user_id2'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_user_id1'), table_name='friendship')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_user_info_user_uuid'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_user_id'), table_name='user_info')
    op.drop_table('user_info')
    # ### end Alembic commands ###