"""Added user info attributes
Revision ID: c60ddfae9002
Revises: ff860b5621fc
Create Date: 2021-06-28 04:39:30.878185
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = 'c60ddfae9002'
down_revision = 'ff860b5621fc'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('share_mode', sa.String(), server_default='default_all', nullable=False))
    op.add_column('user_info', sa.Column('domain_allow_array', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('user_info', sa.Column('domain_deny_array', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('user_info', sa.Column('school', sa.String(), server_default='', nullable=False))
    op.add_column('user_info', sa.Column('school_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_info', sa.Column('work', sa.String(), server_default='', nullable=False))
    op.add_column('user_info', sa.Column('work_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_info', sa.Column('location', sa.String(), server_default='', nullable=False))
    op.add_column('user_info', sa.Column('location_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_info', sa.Column('description', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'description')
    op.drop_column('user_info', 'location_public')
    op.drop_column('user_info', 'location')
    op.drop_column('user_info', 'work_public')
    op.drop_column('user_info', 'work')
    op.drop_column('user_info', 'school_public')
    op.drop_column('user_info', 'school')
    op.drop_column('user_info', 'domain_deny_array')
    op.drop_column('user_info', 'domain_allow_array')
    op.drop_column('user_info', 'share_mode')
    # ### end Alembic commands ###