"""Update UUID column
Revision ID: cbaf738e6d65
Revises: f63f7b075599
Create Date: 2021-06-25 23:44:21.760304
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = 'cbaf738e6d65'
down_revision = 'f63f7b075599'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###