"""Initial migration
Revision ID: f63f7b075599
Revises: 
Create Date: 2021-06-23 09:32:03.883011
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic
revision = 'f63f7b075599'
down_revision = None
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('dob_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_info_user_id'), 'user_info', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_info_user_uuid'), 'user_info', ['user_uuid'], unique=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_user_uuid'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_user_id'), table_name='user_info')
    op.drop_table('user_info')
    # ### end Alembic commands ###